env:
  node: true
  es2021: true

plugins:
  - jest
 
# https://eslint.org/docs/user-guide/configuring#specifying-environments

extends:
  - 'airbnb-base'
  - 'plugin:jest/recommended'
  - "eslint:recommended"
parserOptions:
  ecmaVersion: 12
  sourceType: module

rules:
  no-console: 0
  no-underscore-dangle: [2, { "allow": ["__filename", "__dirname"] }]
  import/extensions: 0 # FIXME: remove when rule will be adjusted for new nodejs version
